"""Add feedback column to messages

Revision ID: 412b6cf3c1e1
Revises: 721f3c2a5424
Create Date: 2026-03-09 21:36:02.653621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '412b6cf3c1e1'
down_revision: Union[str, Sequence[str], None] = '721f3c2a5424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True), )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'feedback', )
    # ### end Alembic commands ###
