"""Add new bot fields and chat tables

Revision ID: 50e4439ee7d7
Revises: 
Create Date: 2026-03-01 00:56:26.082197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50e4439ee7d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bots', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"),
               schema='nexus_core')
    op.alter_column('bots', 'plan_required',
               existing_type=postgresql.ENUM('FREE', 'PRO', name='plantype', schema='nexus_core'),
               type_=sa.Enum('FREE', 'PRO', name='plantype'),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'::nexus_core.plantype"),
               postgresql_using='plan_required::text::nexus_core.plantype',
               schema='nexus_core')
    op.alter_column('bots', 'system_prompt',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"),
               schema='nexus_core')
    op.drop_constraint(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', schema='nexus_core', type_='foreignkey')
    op.drop_constraint(op.f('chat_sessions_bot_id_fkey'), 'chat_sessions', schema='nexus_core', type_='foreignkey')
    op.create_foreign_key(None, 'chat_sessions', 'bots', ['bot_id'], ['id'], source_schema='nexus_core', referent_schema='nexus_core')
    op.create_foreign_key(None, 'chat_sessions', 'users', ['user_id'], ['id'], source_schema='nexus_core', referent_schema='nexus_core')
    op.alter_column('messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', 'system', name='messagerole', schema='nexus_core'),
               type_=sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::nexus_core.messagerole"),
               postgresql_using='role::text::nexus_core.messagerole',
               schema='nexus_core')
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False,
               schema='nexus_core')
    op.drop_constraint(op.f('messages_session_id_fkey'), 'messages', schema='nexus_core', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chat_sessions', ['session_id'], ['id'], source_schema='nexus_core', referent_schema='nexus_core')
    op.alter_column('users', 'plan_type',
               existing_type=postgresql.ENUM('FREE', 'PRO', name='plantype', schema='nexus_core'),
               type_=sa.Enum('FREE', 'PRO', name='plantype'),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'::nexus_core.plantype"),
               postgresql_using='plan_type::text::nexus_core.plantype',
               schema='nexus_core')
    op.drop_constraint(op.f('users_email_key'), 'users', schema='nexus_core', type_='unique')
    op.drop_constraint(op.f('users_supabase_uid_key'), 'users', schema='nexus_core', type_='unique')
    op.drop_index(op.f('ix_nexus_core_users_email'), table_name='users', schema='nexus_core')
    op.create_index(op.f('ix_nexus_core_users_email'), 'users', ['email'], unique=True, schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_users_supabase_uid'), table_name='users', schema='nexus_core')
    op.create_index(op.f('ix_nexus_core_users_supabase_uid'), 'users', ['supabase_uid'], unique=True, schema='nexus_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nexus_core_users_supabase_uid'), table_name='users', schema='nexus_core')
    op.create_index(op.f('ix_nexus_core_users_supabase_uid'), 'users', ['supabase_uid'], unique=False, schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_users_email'), table_name='users', schema='nexus_core')
    op.create_index(op.f('ix_nexus_core_users_email'), 'users', ['email'], unique=False, schema='nexus_core')
    op.create_unique_constraint(op.f('users_supabase_uid_key'), 'users', ['supabase_uid'], schema='nexus_core', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='nexus_core', postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'plan_type',
               existing_type=sa.Enum('FREE', 'PRO', name='plantype'),
               type_=postgresql.ENUM('FREE', 'PRO', name='plantype', schema='nexus_core'),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'::nexus_core.plantype"),
               schema='nexus_core')
    op.drop_constraint(None, 'messages', schema='nexus_core', type_='foreignkey')
    op.create_foreign_key(op.f('messages_session_id_fkey'), 'messages', 'chat_sessions', ['session_id'], ['id'], source_schema='nexus_core', referent_schema='nexus_core', ondelete='CASCADE')
    op.alter_column('messages', 'content',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               schema='nexus_core')
    op.alter_column('messages', 'role',
               existing_type=sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'),
               type_=postgresql.ENUM('user', 'assistant', 'system', name='messagerole', schema='nexus_core'),
               existing_nullable=False,
               existing_server_default=sa.text("'user'::nexus_core.messagerole"),
               schema='nexus_core')
    op.drop_constraint(None, 'chat_sessions', schema='nexus_core', type_='foreignkey')
    op.drop_constraint(None, 'chat_sessions', schema='nexus_core', type_='foreignkey')
    op.create_foreign_key(op.f('chat_sessions_bot_id_fkey'), 'chat_sessions', 'bots', ['bot_id'], ['id'], source_schema='nexus_core', referent_schema='nexus_core', ondelete='SET NULL')
    op.create_foreign_key(op.f('chat_sessions_user_id_fkey'), 'chat_sessions', 'users', ['user_id'], ['id'], source_schema='nexus_core', referent_schema='nexus_core', ondelete='SET NULL')
    op.alter_column('bots', 'system_prompt',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("''::text"),
               schema='nexus_core')
    op.alter_column('bots', 'plan_required',
               existing_type=sa.Enum('FREE', 'PRO', name='plantype'),
               type_=postgresql.ENUM('FREE', 'PRO', name='plantype', schema='nexus_core'),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'::nexus_core.plantype"),
               schema='nexus_core')
    op.alter_column('bots', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"),
               schema='nexus_core')
    # ### end Alembic commands ###
