"""Initial Schema

Revision ID: 721f3c2a5424
Revises: 
Create Date: 2026-03-05 13:20:58.639642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '721f3c2a5424'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_new', sa.Boolean(), nullable=False),
    sa.Column('plan_required', sa.Enum('FREE', 'PRO', name='plantype', schema='nexus_core'), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='nexus_core'
    )
    op.create_index(op.f('ix_nexus_core_bots_name'), 'bots', ['name'], unique=False, schema='nexus_core')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_uid', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('plan_type', sa.Enum('FREE', 'PRO', name='plantype', schema='nexus_core'), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='nexus_core'
    )
    op.create_index(op.f('ix_nexus_core_users_email'), 'users', ['email'], unique=True, schema='nexus_core')
    op.create_index(op.f('ix_nexus_core_users_supabase_uid'), 'users', ['supabase_uid'], unique=True, schema='nexus_core')
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['nexus_core.bots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['nexus_core.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='nexus_core'
    )
    op.create_index(op.f('ix_nexus_core_chat_sessions_bot_id'), 'chat_sessions', ['bot_id'], unique=False, schema='nexus_core')
    op.create_index(op.f('ix_nexus_core_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False, schema='nexus_core')
    op.create_table('faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('question_vector', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['nexus_core.bots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='nexus_core'
    )
    op.create_index(op.f('ix_nexus_core_faqs_bot_id'), 'faqs', ['bot_id'], unique=False, schema='nexus_core')
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='messagerole', schema='nexus_core'), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['nexus_core.chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='nexus_core'
    )
    op.create_index(op.f('ix_nexus_core_messages_session_id'), 'messages', ['session_id'], unique=False, schema='nexus_core')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nexus_core_messages_session_id'), table_name='messages', schema='nexus_core')
    op.drop_table('messages', schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_faqs_bot_id'), table_name='faqs', schema='nexus_core')
    op.drop_table('faqs', schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_chat_sessions_user_id'), table_name='chat_sessions', schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_chat_sessions_bot_id'), table_name='chat_sessions', schema='nexus_core')
    op.drop_table('chat_sessions', schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_users_supabase_uid'), table_name='users', schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_users_email'), table_name='users', schema='nexus_core')
    op.drop_table('users', schema='nexus_core')
    op.drop_index(op.f('ix_nexus_core_bots_name'), table_name='bots', schema='nexus_core')
    op.drop_table('bots', schema='nexus_core')
    # ### end Alembic commands ###
