"""add_redteam_tables

Revision ID: f3ab5cee1278
Revises: f3a9b1c8d2e7
Create Date: 2026-06-25 22:36:42.628904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3ab5cee1278'
down_revision: Union[str, Sequence[str], None] = 'f3a9b1c8d2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redteam_question_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category_source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redteam_question_groups_category'), 'redteam_question_groups', ['category'], unique=False)
    op.create_index(op.f('ix_redteam_question_groups_question_norm'), 'redteam_question_groups', ['question_norm'], unique=False)
    op.create_table('redteam_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('submitter', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('question', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_norm', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('risk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bot_responses', sa.JSON(), nullable=True),
    sa.Column('feedback_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('match_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['redteam_question_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redteam_responses_group_id'), 'redteam_responses', ['group_id'], unique=False)
    op.create_index(op.f('ix_redteam_responses_question_norm'), 'redteam_responses', ['question_norm'], unique=False)
    op.create_index(op.f('ix_redteam_responses_week'), 'redteam_responses', ['week'], unique=False)
    op.create_table('redteam_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('reviewer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('correct_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('week1_reflect', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('week2_reflect', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('week3_reflect', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['redteam_question_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'reviewer', name='uq_redteam_review_group_reviewer')
    )
    op.create_index(op.f('ix_redteam_reviews_group_id'), 'redteam_reviews', ['group_id'], unique=False)
    op.create_index(op.f('ix_redteam_reviews_reviewer'), 'redteam_reviews', ['reviewer'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_redteam_reviews_reviewer'), table_name='redteam_reviews')
    op.drop_index(op.f('ix_redteam_reviews_group_id'), table_name='redteam_reviews')
    op.drop_table('redteam_reviews')
    op.drop_index(op.f('ix_redteam_responses_week'), table_name='redteam_responses')
    op.drop_index(op.f('ix_redteam_responses_question_norm'), table_name='redteam_responses')
    op.drop_index(op.f('ix_redteam_responses_group_id'), table_name='redteam_responses')
    op.drop_table('redteam_responses')
    op.drop_index(op.f('ix_redteam_question_groups_question_norm'), table_name='redteam_question_groups')
    op.drop_index(op.f('ix_redteam_question_groups_category'), table_name='redteam_question_groups')
    op.drop_table('redteam_question_groups')
    # ### end Alembic commands ###
